version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - db_network
    volumes:
      - ./volume/:/app/app/volume
      - ./media/:/app/app/media
    ports:
      - 8888:8888
    command: "npm run start:prod"
networks:
  db_network:
    name: db_network
    external: true